nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin:
            - "https://project-manager.costincianu.fr"
            - "http://localhost:5173"
        allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        allow_headers: ["Content-Type", "Authorization"]
        max_age: 3600
    paths:
        "^/api":
            allow_origin:
                - "https://project-manager.costincianu.fr"
                - "http://localhost:5173"
            allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            allow_headers: ["Content-Type", "Authorization"]
            max_age: 3600
